#!/bin/bash

#install deps
pip install boto3
yum update -y
yum install -y wget git

#pull down the analysis script and run it
mkdir /tools
cd /tools
git clone https://github.com/VanAndelInstitute/su2caws.git

#the actual line to call the analysisi will go after this, it should look like the following:
python /tools/su2caws/vaisu2c/AwsS3.py su2ctest/test/data1.txt
#dont forget to call 'shutdown -h now' so that the instance terminates when done!
#these will be generated by lambda and passed to the instance creation call.
